src/objects/ProductReview__c.object
<CustomObject>
    <fields>
        <fullName>ProductId__c</fullName>
        <label>ProductId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ProductReview</label>
    <nameField>
        <label>ProductReview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductReviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BC_CommunityProductViewController.cls
public with sharing class BC_CommunityProductViewController {
    @AuraEnabled
    public static BC_RatingWrapper getRating(String productId) {
        BC_RatingWrapper productRatingAndVotes = new BC_RatingWrapper();
        Double ratingSum = 0;

        List<ProductReview__c> productReviews = new List<ProductReview__c>();
        productReviews = [SELECT Rating__c FROM ProductReview__c WHERE ProductId__c =:productId];
        for(ProductReview__c review : productReviews) {
            ratingSum += review.Rating__c;
        }

        if(productReviews.size() > 0){
            productRatingAndVotes.vote_count = productReviews.size();
            productRatingAndVotes.vote_average = ratingSum / productRatingAndVotes.vote_count;
        }
        
        return productRatingAndVotes;
    }
    
    @AuraEnabled
    public static Boolean addItemFromView(String product) {
        return BC_BasketController.addItemToBasketCache(product);
    }
}